declare namespace Math {
    const E: number;
    const LN10: number;
    const LN2: number;
    const LOG10E: number;
    const LOG2E: number;
    const PI: number;
    const SQRT1_2: number;
    const SQRT2: number;
    function abs(p0: any): any;
    function acos(p0: any): any;
    function acosh(p0: any): any;
    function asin(p0: any): any;
    function asinh(p0: any): any;
    function atan(p0: any): any;
    function atan2(p0: any, p1: any): any;
    function atanh(p0: any): any;
    function cbrt(p0: any): any;
    function ceil(p0: any): any;
    function clz32(p0: any): any;
    function cos(p0: any): any;
    function cosh(p0: any): any;
    function exp(p0: any): any;
    function expm1(p0: any): any;
    function floor(p0: any): any;
    function fround(p0: any): any;
    function hypot(p0: any, p1: any): any;
    function imul(p0: any, p1: any): any;
    function log(p0: any): any;
    function log10(p0: any): any;
    function log1p(p0: any): any;
    function log2(p0: any): any;
    function max(p0: any, p1: any): any;
    function min(p0: any, p1: any): any;
    function pow(p0: any, p1: any): any;
    function random(): any;
    function round(p0: any): any;
    function sign(p0: any): any;
    function sin(p0: any): any;
    function sinh(p0: any): any;
    function sqrt(p0: any): any;
    function tan(p0: any): any;
    function tanh(p0: any): any;
    function trunc(p0: any): any;
}
